# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win(object):
    def setupUi(self, win):
        win.setObjectName("win")
        win.setEnabled(True)
        win.resize(440, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(win.sizePolicy().hasHeightForWidth())
        win.setSizePolicy(sizePolicy)
        win.setMinimumSize(QtCore.QSize(440, 440))
        win.setMaximumSize(QtCore.QSize(440, 500))
        win.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(win)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(80, 10, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.guess_input = QtWidgets.QFrame(self.centralwidget)
        self.guess_input.setGeometry(QtCore.QRect(30, 133, 381, 81))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.guess_input.setFont(font)
        self.guess_input.setFocusPolicy(QtCore.Qt.TabFocus)
        self.guess_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.guess_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.guess_input.setObjectName("guess_input")
        self.guess_input_1 = QtWidgets.QLineEdit(self.guess_input)
        self.guess_input_1.setGeometry(QtCore.QRect(0, 0, 81, 81))
        self.guess_input_1.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.guess_input_1.setObjectName("guess_input_1")
        self.guess_input_2 = QtWidgets.QLineEdit(self.guess_input)
        self.guess_input_2.setGeometry(QtCore.QRect(100, 0, 81, 81))
        self.guess_input_2.setObjectName("guess_input_2")
        self.guess_input_3 = QtWidgets.QLineEdit(self.guess_input)
        self.guess_input_3.setGeometry(QtCore.QRect(200, 0, 81, 81))
        self.guess_input_3.setObjectName("guess_input_3")
        self.guess_input_4 = QtWidgets.QLineEdit(self.guess_input)
        self.guess_input_4.setGeometry(QtCore.QRect(300, 0, 81, 81))
        self.guess_input_4.setObjectName("guess_input_4")
        self.check_btn = QtWidgets.QPushButton(self.centralwidget)
        self.check_btn.setGeometry(QtCore.QRect(30, 240, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.check_btn.setFont(font)
        self.check_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_btn.setObjectName("check_btn")
        self.life = QtWidgets.QLabel(self.centralwidget)
        self.life.setGeometry(QtCore.QRect(20, 70, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.life.setFont(font)
        self.life.setObjectName("life")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 310, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 350, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        win.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 26))
        self.menubar.setObjectName("menubar")
        win.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(win)
        self.statusbar.setObjectName("statusbar")
        win.setStatusBar(self.statusbar)

        self.retranslateUi(win)
        QtCore.QMetaObject.connectSlotsByName(win)

    def retranslateUi(self, win):
        _translate = QtCore.QCoreApplication.translate
        win.setWindowTitle(_translate("win", "MainWindow"))
        self.title.setText(_translate("win", "Guess the Number"))
        self.check_btn.setText(_translate("win", "Check"))
        self.life.setText(_translate("win", "🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤"))
        self.label.setText(_translate("win", "2 numbers are in the right position"))
        self.label_2.setText(_translate("win", "1 numbers is correct but in the wrong position"))

    def check(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    ui = Ui_win()
    ui.setupUi(win)
    win.show()
    sys.exit(app.exec_())
